apiVersion: batch/v1
kind: Job
metadata: 
  name: redis-client
  labels:
    app: redis-client
spec:
  template:
    metadata:
      labels:
        app: redis-client
      annotations:
        argocd.argoproj.io/hook: PostSync
        argocd.argoproj.io/hook-delete-policy: HookSucceeded
    spec:
      affinity:
        podAffinity: 
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/instance
                operator: In
                values:
                - {{ .Values.podName }}
            topologyKey: {{ .Values.topologyKey }}
      securityContext: 
        runAsUser: 0
      containers:
        - name: redis-client
          image: docker.io/bitnami/redis:7.2.5-debian-12-r0
          command: ["bin/bash", "-c", {{ .Values.benchmark }}]
          env:
          - name: REDIS_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: redis
                key: redis-password
          volumeMounts:
          - mountPath: /clientdata/benchmark
            name: test-data
      restartPolicy: Never
      volumes:
      - name: test-data
        persistentVolumeClaim: 
          claimName: redis-test-data